import type { ToolDefinition } from './types';
import type { ToolModuleLoader } from './module-types';

export interface ToolManifestEntry extends ToolDefinition {
  moduleLoader?: ToolModuleLoader;
}

export const toolsManifest = [
  {
    id: 'merge-pdf',
    slug: 'merge',
    title: 'Merge PDF',
    path: '/merge',
    description:
      'Combine PDFs in the order you choose directly in your browser.',
    status: 'ready',
    category: 'organize',
    localOnly: true,
    inputKinds: ['pdf'],
    outputKinds: ['pdf'],
    supportsBatch: true,
    estimatedComplexity: 'low',
    workspaceMode: 'standard',
    moduleLoader: async () => import('~/features/merge/module'),
  },
  {
    id: 'pdf-info',
    slug: 'info',
    title: 'PDF Info',
    path: '/info',
    description:
      'Extract metadata, producer/creator fields, and font insights locally.',
    status: 'ready',
    category: 'advanced',
    localOnly: true,
    inputKinds: ['pdf'],
    outputKinds: ['none'],
    supportsBatch: false,
    estimatedComplexity: 'medium',
    workspaceMode: 'standard',
    moduleLoader: async () => import('~/features/pdf-info/module'),
  },
  {
    id: 'crop-pdf-new',
    slug: 'crop',
    title: 'Crop PDF',
    path: '/crop',
    description:
      'Jump directly into single-page crop mode with page navigation controls.',
    status: 'ready',
    category: 'organize',
    localOnly: true,
    inputKinds: ['pdf'],
    outputKinds: ['pdf'],
    supportsBatch: false,
    estimatedComplexity: 'medium',
    workspaceMode: 'custom',
    moduleLoader: async () => import('~/features/crop/module'),
  },
  {
    id: 'split-pdf',
    slug: 'split',
    title: 'Split PDF',
    path: '/split',
    description: 'Extract pages or ranges into separate files.',
    status: 'ready',
    category: 'organize',
    localOnly: true,
    inputKinds: ['pdf'],
    outputKinds: ['pdf'],
    supportsBatch: false,
    estimatedComplexity: 'low',
    workspaceMode: 'standard',
    moduleLoader: async () => import('~/features/split/module'),
  },
  {
    id: 'compress-pdf',
    slug: 'compress',
    title: 'Compress PDF',
    path: '/compress',
    description: 'Reduce PDF size while preserving readable quality.',
    status: 'coming_soon',
    category: 'optimize',
    localOnly: true,
    inputKinds: ['pdf'],
    outputKinds: ['pdf'],
    supportsBatch: true,
    estimatedComplexity: 'medium',
    workspaceMode: 'standard',
  },
  {
    id: 'image-to-pdf',
    slug: 'image-to-pdf',
    title: 'Image to PDF',
    path: '/image-to-pdf',
    description: 'Convert JPG and PNG images into a single PDF.',
    status: 'ready',
    category: 'convert',
    localOnly: true,
    inputKinds: ['jpg', 'png', 'image'],
    outputKinds: ['pdf'],
    supportsBatch: true,
    estimatedComplexity: 'low',
    workspaceMode: 'standard',
    moduleLoader: async () => import('~/features/image-to-pdf/module'),
  },
  {
    id: 'pdf-to-images',
    slug: 'pdf-to-images',
    title: 'PDF to Images',
    path: '/pdf-to-images',
    description: 'Convert PDF pages into image files and download as a ZIP.',
    status: 'ready',
    category: 'convert',
    localOnly: true,
    inputKinds: ['pdf'],
    outputKinds: ['images'],
    supportsBatch: false,
    estimatedComplexity: 'medium',
    workspaceMode: 'standard',
    moduleLoader: async () => import('~/features/pdf-to-images/module'),
  },
  {
    id: 'organize-pdf',
    slug: 'organize',
    title: 'Organize PDF',
    path: '/organize',
    description: 'Reorder, rotate, and delete pages before saving.',
    status: 'ready',
    category: 'organize',
    localOnly: true,
    inputKinds: ['pdf'],
    outputKinds: ['pdf'],
    supportsBatch: false,
    estimatedComplexity: 'medium',
    workspaceMode: 'custom',
    moduleLoader: async () => import('~/features/organize/module'),
  },
  {
    id: 'extract-images',
    slug: 'extract-images',
    title: 'Extract Images',
    path: '/extract-images',
    description: 'Extract embedded images from PDF files.',
    status: 'coming_soon',
    category: 'advanced',
    localOnly: true,
    inputKinds: ['pdf'],
    outputKinds: ['images'],
    supportsBatch: false,
    estimatedComplexity: 'high',
    workspaceMode: 'custom',
  },
  {
    id: 'rename-files',
    slug: 'rename',
    title: 'Rename',
    path: '/rename',
    description: 'Bulk rename files with predictable naming rules.',
    status: 'coming_soon',
    category: 'organize',
    localOnly: true,
    inputKinds: ['folder', 'pdf', 'image'],
    outputKinds: ['none'],
    supportsBatch: true,
    estimatedComplexity: 'low',
    workspaceMode: 'standard',
  },
  {
    id: 'watermark-pdf',
    slug: 'watermark',
    title: 'Watermark',
    path: '/watermark',
    description: 'Add text watermark overlays to every page.',
    status: 'coming_soon',
    category: 'secure',
    localOnly: true,
    inputKinds: ['pdf'],
    outputKinds: ['pdf'],
    supportsBatch: true,
    estimatedComplexity: 'medium',
    workspaceMode: 'standard',
  },
  {
    id: 'page-numbers',
    slug: 'page-numbers',
    title: 'Page Numbers',
    path: '/page-numbers',
    description: 'Add page numbers with configurable format and position.',
    status: 'coming_soon',
    category: 'organize',
    localOnly: true,
    inputKinds: ['pdf'],
    outputKinds: ['pdf'],
    supportsBatch: true,
    estimatedComplexity: 'medium',
    workspaceMode: 'standard',
  },
  {
    id: 'remove-blank',
    slug: 'remove-blank',
    title: 'Remove Blank',
    path: '/remove-blank',
    description: 'Detect and remove blank pages automatically.',
    status: 'coming_soon',
    category: 'optimize',
    localOnly: true,
    inputKinds: ['pdf'],
    outputKinds: ['pdf'],
    supportsBatch: true,
    estimatedComplexity: 'medium',
    workspaceMode: 'standard',
  },
  {
    id: 'optimize-pdf',
    slug: 'optimize',
    title: 'Optimize',
    path: '/optimize',
    description: 'Optimize structure and remove unnecessary metadata.',
    status: 'coming_soon',
    category: 'optimize',
    localOnly: true,
    inputKinds: ['pdf'],
    outputKinds: ['pdf'],
    supportsBatch: true,
    estimatedComplexity: 'high',
    workspaceMode: 'standard',
  },
  {
    id: 'protect-pdf',
    slug: 'protect',
    title: 'Protect',
    path: '/protect',
    description: 'Encrypt PDF files with a password.',
    status: 'coming_soon',
    category: 'secure',
    localOnly: true,
    inputKinds: ['pdf'],
    outputKinds: ['pdf'],
    supportsBatch: true,
    estimatedComplexity: 'medium',
    workspaceMode: 'standard',
  },
  {
    id: 'unlock-pdf',
    slug: 'unlock',
    title: 'Unlock',
    path: '/unlock',
    description: 'Remove known password protection from PDF files.',
    status: 'coming_soon',
    category: 'secure',
    localOnly: true,
    inputKinds: ['pdf'],
    outputKinds: ['pdf'],
    supportsBatch: true,
    estimatedComplexity: 'medium',
    workspaceMode: 'standard',
  },
  {
    id: 'searchable-pdf',
    slug: 'searchable-pdf',
    title: 'Searchable PDF',
    path: '/searchable-pdf',
    description: 'Run OCR locally to make scanned PDF text searchable.',
    status: 'coming_soon',
    category: 'advanced',
    localOnly: true,
    inputKinds: ['scanned_pdf', 'pdf'],
    outputKinds: ['pdf'],
    supportsBatch: false,
    estimatedComplexity: 'high',
    workspaceMode: 'custom',
  },
  {
    id: 'extract-text',
    slug: 'extract-text',
    title: 'Extract Text',
    path: '/extract-text',
    description: 'Extract text from scanned documents with OCR.',
    status: 'coming_soon',
    category: 'advanced',
    localOnly: true,
    inputKinds: ['scanned_pdf', 'pdf'],
    outputKinds: ['text'],
    supportsBatch: false,
    estimatedComplexity: 'high',
    workspaceMode: 'custom',
  },
  {
    id: 'smart-search',
    slug: 'smart-search',
    title: 'Smart Search',
    path: '/smart-search',
    description: 'Search scanned PDFs by OCR-derived text index.',
    status: 'coming_soon',
    category: 'advanced',
    localOnly: true,
    inputKinds: ['scanned_pdf', 'pdf'],
    outputKinds: ['none'],
    supportsBatch: false,
    estimatedComplexity: 'high',
    workspaceMode: 'custom',
  },
  {
    id: 'read-aloud',
    slug: 'read-aloud',
    title: 'Read Aloud',
    path: '/read-aloud',
    description: 'Read extracted PDF text with in-browser text-to-speech.',
    status: 'coming_soon',
    category: 'advanced',
    localOnly: true,
    inputKinds: ['pdf'],
    outputKinds: ['audio'],
    supportsBatch: false,
    estimatedComplexity: 'high',
    workspaceMode: 'custom',
  },
  {
    id: 'redact-text',
    slug: 'redact-text',
    title: 'Redact Text',
    path: '/redact-text',
    description: 'Securely blackout sensitive text selections in PDFs.',
    status: 'coming_soon',
    category: 'secure',
    localOnly: true,
    inputKinds: ['pdf'],
    outputKinds: ['pdf'],
    supportsBatch: false,
    estimatedComplexity: 'high',
    workspaceMode: 'custom',
  },
] as const satisfies readonly ToolManifestEntry[];
